In [2]:
import numpy as np


In [3]:
# Creating numpy Array

In [4]:
my_list = [1, 2, 3]

In [5]:
x = np.array(my_list)

In [6]:
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [8]:
type(my_matrix)

list

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [11]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(3)


array([0., 0., 0.])

In [14]:
type(1)


int

In [15]:
type(1.0)

float

In [16]:
np.ones(4, 5)

TypeError: Cannot interpret '5' as a data type

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:

np.linspace(0, 10, 30)

array([[ 0. ,  1. ,  2. ,  3. ,  4. ],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [10. , 10. , 10. , 10. , 10. ]])

In [20]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
np.linspace(0, 10, 1)


array([0.])

In [22]:
np(0, 12, 2)

TypeError: 'module' object is not callable

In [23]:
np.linspace(0, 12, 3)

array([ 0.,  6., 12.])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(1)

array([0.26015661])

In [29]:
np.random(5, 4)

TypeError: 'module' object is not callable

In [30]:
np.random.rand(5, 4)

array([[0.37877153, 0.14407489, 0.85265853, 0.88507951],
       [0.89920899, 0.54174269, 0.6020463 , 0.52344852],
       [0.00344744, 0.62320443, 0.48525332, 0.00375746],
       [0.78335608, 0.54956707, 0.98198242, 0.3408501 ],
       [0.21927691, 0.7630365 , 0.56895584, 0.97247759]])

In [31]:
np.random.randn(5)

array([ 0.03467079, -0.93584212, -0.22728916, -2.14503987,  0.15169915])

In [32]:
# Standard Normal Dist is randn

In [33]:
np.random.randn(5, 4)

array([[-0.3338508 ,  0.54956227,  0.07135671, -0.08688897],
       [ 0.8709522 , -0.0619973 , -0.52100052, -1.33297242],
       [-0.79465778, -0.13273472,  1.70922399,  0.33626259],
       [ 1.66126374, -0.70412015,  1.41362599,  0.2974779 ],
       [-0.83034448,  0.62461879,  1.4355377 , -0.45240485]])

In [34]:
np.random.randint(1, 100)

60

In [38]:
[np.random.randint(1, 100) for x in range(10)]

[82, 18, 96, 43, 49, 31, 42, 66, 69, 87]

In [39]:
np.random.randint(1, 100, 10)

array([ 6, 41, 47, 69, 78,  3, 65, 75, 35, 79])

In [40]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr

array([48,  8, 33, 49, 34,  3,  2, 46, 21,  4])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr = np.random.randint(0, 100, 20)

In [46]:
arr.reshape(5, 4)

array([[96, 95,  5, 29],
       [57, 28, 51,  3],
       [81, 94, 24, 43],
       [17, 67, 54, 38],
       [ 3, 64, 11, 99]])

In [47]:
arr.shape

(20,)

In [48]:
arr = arr.reshape(5, 4)

In [49]:
arr.shape

(5, 4)

In [50]:
arr.reshape(20, 1)

array([[96],
       [95],
       [ 5],
       [29],
       [57],
       [28],
       [51],
       [ 3],
       [81],
       [94],
       [24],
       [43],
       [17],
       [67],
       [54],
       [38],
       [ 3],
       [64],
       [11],
       [99]])

In [51]:
arr = arr.reshape(20, 1)

In [52]:
arr

array([[96],
       [95],
       [ 5],
       [29],
       [57],
       [28],
       [51],
       [ 3],
       [81],
       [94],
       [24],
       [43],
       [17],
       [67],
       [54],
       [38],
       [ 3],
       [64],
       [11],
       [99]])

In [53]:
arr.shape

(20, 1)

In [54]:
arr.dtype

dtype('int32')

In [55]:
arr.max()

99

In [56]:
arr.argmax()

19

In [57]:
arr

array([[96],
       [95],
       [ 5],
       [29],
       [57],
       [28],
       [51],
       [ 3],
       [81],
       [94],
       [24],
       [43],
       [17],
       [67],
       [54],
       [38],
       [ 3],
       [64],
       [11],
       [99]])

In [58]:
arr.min

<function ndarray.min>

In [59]:
arr.min()

3

In [60]:
arr.argmin()

7