In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[0:3]

array([0, 1, 2])

In [6]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
# Broadcast function

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr [0:5] = 75 #  Known as broadcasting

In [11]:
arr

array([75, 75, 75, 75, 75,  5,  6,  7,  8,  9, 10])

In [12]:
arr = np.arange(0, 11)

In [13]:
slice_of_arr = arr[0:5]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [23]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 0

In [25]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [27]:
# 2D Array matrix[row, col] or matrix[row][col]

In [28]:
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [29]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
mat[0]

array([ 5, 10, 15])

In [31]:
mat[,3]

SyntaxError: invalid syntax (<ipython-input-31-d5e471893048>, line 1)

In [32]:
mat[,2]

SyntaxError: invalid syntax (<ipython-input-32-ff0194fb6760>, line 1)

In [33]:
mat[][3]

SyntaxError: invalid syntax (<ipython-input-33-74cdc62dbb05>, line 1)

In [34]:
mat[1][1]

25

In [35]:
mat[:][1]

array([20, 25, 30])

In [36]:
mat[0][2]

15

In [37]:
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [38]:
mat[1:, :2]

array([[20, 25],
       [35, 40]])

In [39]:
# Conditional Selection

In [40]:
arr = np.arange(0, 11)

In [41]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [42]:
bool_arr = arr > 4

In [43]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])